[loggers]
keys=root,app,api

[handlers]
keys=console,file,errorFile

[formatters]
keys=detailed,simple,json

[logger_root]
level=WARNING
handlers=console

[logger_app]
level=DEBUG
handlers=console,file
qualname=app
propagate=0

[logger_api]
level=INFO
handlers=console,errorFile
qualname=api
propagate=0

[handler_console]
class=StreamHandler
level=INFO
formatter=simple
args=(sys.stdout,)

[handler_file]
class=FileHandler
level=DEBUG
formatter=detailed
args=('config/app.log', 'a')

[handler_errorFile]
class=FileHandler
level=ERROR
formatter=detailed
args=('config/errors.log', 'a')

[formatter_detailed]
format=%(asctime)s | %(levelname)-8s | %(name)s:%(lineno)d | %(message)s
datefmt=%Y-%m-%d %H:%M:%S

[formatter_simple]
format=%(levelname)-8s | %(message)s

[formatter_json]
class=lesson.JSONFormatter
